// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbMCEsOZhvddXlTRaT9szFjWyq6sAqK6c',
    appId: '1:354428054862:web:832dd495624f36560c421f',
    messagingSenderId: '354428054862',
    projectId: 'pettalks',
    authDomain: 'pettalks.firebaseapp.com',
    storageBucket: 'pettalks.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCulTUdRt2jDqlNSHTiyk8Qg94PbqSbClo',
    appId: '1:354428054862:android:34492403bc1c37cb0c421f',
    messagingSenderId: '354428054862',
    projectId: 'pettalks',
    storageBucket: 'pettalks.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTdJCyE1vSvcbB0QHn7WYT5V6CYaD69yY',
    appId: '1:354428054862:ios:983da22d1afec9cb0c421f',
    messagingSenderId: '354428054862',
    projectId: 'pettalks',
    storageBucket: 'pettalks.firebasestorage.app',
    iosBundleId: 'com.example.pettalks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTdJCyE1vSvcbB0QHn7WYT5V6CYaD69yY',
    appId: '1:354428054862:ios:983da22d1afec9cb0c421f',
    messagingSenderId: '354428054862',
    projectId: 'pettalks',
    storageBucket: 'pettalks.firebasestorage.app',
    iosBundleId: 'com.example.pettalks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbMCEsOZhvddXlTRaT9szFjWyq6sAqK6c',
    appId: '1:354428054862:web:8d05238903c92c740c421f',
    messagingSenderId: '354428054862',
    projectId: 'pettalks',
    authDomain: 'pettalks.firebaseapp.com',
    storageBucket: 'pettalks.firebasestorage.app',
  );
}
